### ISSUE TITLE
Event Trigger QTM

### ISSUE THREAD

**Issue by cafeciaojoe** [qualisys/crazyflie-resources#2]
This may well be a QTM issue, but I thought I'd raise it here in case anyone else finds it useful. 
I have:
Deleted all the event short cuts (there were a punch of blank ones, not sure why)
Reset the synchronisation settings for all cameras. 

Connected to QTM, version Version set to 1.17
Getting parameters from QTM...
Starting to record new measurement in QTM...
Starting listening to QTM packet stream...
Found 1 6DoF bodies defined in QTM project:
        (0) Name
        (1) RGBColor
        (2) Point
QTM capture started - Starting measurement
QTM Event received: QRTEvent.EventCaptureStarted
Unhandled Error
Traceback (most recent call last):
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\twisted\internet\tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\twisted\internet\tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\twisted\internet\endpoints.py", line 125, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\qtm\protocol.py", line 90, in dataReceived
    self.parse_received(data[h_size:size], type_)
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\site-packages\qtm\protocol.py", line 116, in parse_received
    self.on_event(event)
  File "example-simple-hover.py", line 91, in on_qtm_event
    if event == qtm.QRTEvent.EventTrigger:
  File "C:\Users\jnld\Anaconda3\envs\chiplay\lib\enum.py", line 348, in __getattr__
    raise AttributeError(name) from None
builtins.AttributeError: EventTrigger

Terminating due to QTM disconnect, reason: EventTrigger

**Comment by mbaytas** [comment]
> Deleted all the event short cuts (there were a punch of blank ones, not sure why)
> Reset the synchronisation settings for all cameras.

These actions have to do with features that don't seem to be relevant to the problem at hand.

Could you provide more details, such as: Is this a Miqus or Oqus system? Do you have a wired or wireless trigger ([as seen here](https://www.qualisys.com/hardware/accessories/other-accessories/)) connected to the system? Which one? Which particular script are you running? Does the error arise immediately when you run the script, or upon pressing the trigger button? Are you using the trigger to start and stop capture?
